### ISSUE TITLE
Question regarding the overall functionality of the system

### ISSUE THREAD

**Issue by mkocustos** [ysangkok/mitre-datalog.js#1]
Sorry for this issue, but I could not find any information to contact you directly. I'm interested in the overall behaviour of your system. My question is how the communication between the web server and the Datalog is done. More precisely, how do you send the Datalog clauses from the web server to the datalog program. As far as I understood you're using the datalog.lua file, right? but how do you then realise the parsing of the Datalog clauses? Is it also done in Lua? Or are you sending the Datalog clauses to the C-version of Datalog that parses and runs the program for you?

Thanks and best regards (direct contact information is available on my profile page)

**Comment by ysangkok** [comment]
It's all client side, the web server does nothing except hosting. MITRE Datalog (written in C) is compiled, with it's Lua interpreter, using Emscripten, to JavaScript. Datalog is parsed in C.

The Datalog and Lua is passed to C over Emscripten's virtual filesystem: https://github.com/ysangkok/mitre-datalog.js/blob/master/wrapper.html#L11

The files are read from C using old school POSIX I/O (fopen and company).

I'm happy to answer your questions.
